import type { ActionMeta, PropDef } from "./schema.js";

/**
 * Built-in action metadata. This file must stay free of runtime
 * dependencies (no Node APIs) so the Designer can use it in the browser.
 * Runtime implementations live in @zamtest/actions, except the control
 * flow containers which are executed by the engine itself.
 */

const output = (label = "Save result to"): PropDef => ({
  name: "output",
  label,
  type: "variable",
  output: true,
  description: "Variable that receives the result",
});

const healing: PropDef[] = [
  {
    name: "description",
    label: "Target description",
    type: "string",
    description: "Plain-language description of the element (e.g. 'the blue Login button'). Used by AI to heal broken selectors.",
  },
  {
    name: "aiHeal",
    label: "AI self-healing",
    type: "boolean",
    default: true,
    description: "If the selector fails, ask AI for a replacement selector and retry once.",
  },
];

export const CONTROL_FLOW_TYPES = new Set([
  "core.sequence",
  "core.if",
  "core.forEach",
  "core.while",
  "core.tryCatch",
  "core.break",
]);

export const BUILTIN_ACTIONS: ActionMeta[] = [
  /* ----------------------------- Control flow ----------------------------- */
  {
    type: "core.sequence",
    displayName: "Sequence",
    category: "Control Flow",
    description: "Runs child actions in order.",
    icon: "list",
    props: [],
    slots: ["body"],
  },
  {
    type: "core.if",
    displayName: "If",
    category: "Control Flow",
    description: "Runs 'then' when the condition is truthy, otherwise 'else'.",
    icon: "split",
    props: [{ name: "condition", label: "Condition", type: "expression", required: true }],
    slots: ["then", "else"],
  },
  {
    type: "core.forEach",
    displayName: "For Each",
    category: "Control Flow",
    description: "Runs the body once per item in a list.",
    icon: "repeat",
    props: [
      { name: "items", label: "Items", type: "expression", required: true },
      { name: "itemVariable", label: "Item variable", type: "variable", default: "item" },
      { name: "indexVariable", label: "Index variable", type: "variable" },
    ],
    slots: ["body"],
  },
  {
    type: "core.while",
    displayName: "While",
    category: "Control Flow",
    description: "Repeats the body while the condition is truthy.",
    icon: "loop",
    props: [
      { name: "condition", label: "Condition", type: "expression", required: true },
      { name: "maxIterations", label: "Max iterations", type: "number", default: 1000 },
    ],
    slots: ["body"],
  },
  {
    type: "core.tryCatch",
    displayName: "Try / Catch",
    category: "Control Flow",
    description: "Handles errors raised by the 'try' block.",
    icon: "shield",
    props: [{ name: "errorVariable", label: "Error variable", type: "variable", default: "error" }],
    slots: ["try", "catch", "finally"],
  },
  {
    type: "core.break",
    displayName: "Break",
    category: "Control Flow",
    description: "Exits the nearest For Each / While loop.",
    icon: "stop",
    props: [],
  },
  {
    type: "core.throw",
    displayName: "Throw",
    category: "Control Flow",
    description: "Raises a business or system exception.",
    icon: "alert",
    props: [{ name: "message", label: "Message", type: "string", required: true }],
  },

  /* -------------------------------- System -------------------------------- */
  {
    type: "core.log",
    displayName: "Log Message",
    category: "System",
    description: "Writes a message to the job log.",
    icon: "message",
    props: [
      { name: "message", label: "Message", type: "string", required: true },
      { name: "level", label: "Level", type: "enum", options: ["debug", "info", "warn", "error"], default: "info" },
    ],
  },
  {
    type: "core.assign",
    displayName: "Assign",
    category: "System",
    description: "Sets a variable to the value of an expression.",
    icon: "equals",
    props: [
      { name: "variable", label: "Variable", type: "variable", required: true, output: true },
      { name: "value", label: "Value", type: "expression", required: true },
    ],
  },
  {
    type: "core.delay",
    displayName: "Delay",
    category: "System",
    description: "Waits for a number of milliseconds.",
    icon: "clock",
    props: [{ name: "ms", label: "Milliseconds", type: "number", default: 1000, required: true }],
  },
  {
    type: "core.comment",
    displayName: "Comment",
    category: "System",
    description: "Documentation only; does nothing at run time.",
    icon: "note",
    props: [{ name: "text", label: "Text", type: "text" }],
  },
  {
    type: "core.getAsset",
    displayName: "Get Asset",
    category: "System",
    description: "Reads a shared asset or credential from the Portal.",
    icon: "key",
    props: [{ name: "name", label: "Asset name", type: "string", required: true }, output("Save value to")],
  },
  {
    type: "core.runScript",
    displayName: "Run JavaScript",
    category: "System",
    description: "Runs a JavaScript snippet. Workflow variables are available as `vars`; the return value is saved to the output.",
    icon: "code",
    props: [{ name: "code", label: "Code", type: "text", required: true }, output()],
  },

  /* --------------------------------- Data --------------------------------- */
  {
    type: "data.httpRequest",
    displayName: "HTTP Request",
    category: "Data & Integration",
    description: "Calls a REST API. Result: { status, headers, body }.",
    icon: "globe",
    agentTool: true,
    props: [
      { name: "method", label: "Method", type: "enum", options: ["GET", "POST", "PUT", "PATCH", "DELETE"], default: "GET" },
      { name: "url", label: "URL", type: "string", required: true },
      { name: "headers", label: "Headers", type: "json" },
      { name: "body", label: "Body", type: "json" },
      output(),
    ],
  },
  {
    type: "data.parseJson",
    displayName: "Parse JSON",
    category: "Data & Integration",
    description: "Parses a JSON string into an object.",
    icon: "braces",
    props: [{ name: "text", label: "JSON text", type: "string", required: true }, output()],
  },
  {
    type: "file.read",
    displayName: "Read File",
    category: "Files",
    description: "Reads a text file.",
    icon: "file",
    agentTool: true,
    props: [{ name: "path", label: "Path", type: "string", required: true }, output()],
  },
  {
    type: "file.write",
    displayName: "Write File",
    category: "Files",
    description: "Writes (or appends) text to a file.",
    icon: "save",
    props: [
      { name: "path", label: "Path", type: "string", required: true },
      { name: "content", label: "Content", type: "string", required: true },
      { name: "append", label: "Append", type: "boolean", default: false },
    ],
  },

  /* -------------------------------- Browser ------------------------------- */
  {
    type: "browser.open",
    displayName: "Open Browser",
    category: "Browser",
    description: "Launches a browser and opens a URL.",
    icon: "browser",
    props: [
      { name: "url", label: "URL", type: "string", required: true },
      { name: "browser", label: "Browser", type: "enum", options: ["chromium", "firefox", "webkit"], default: "chromium" },
      { name: "headless", label: "Headless", type: "boolean", default: false },
    ],
  },
  {
    type: "browser.navigate",
    displayName: "Navigate To",
    category: "Browser",
    description: "Navigates the open browser to a URL.",
    icon: "arrow",
    agentTool: true,
    props: [{ name: "url", label: "URL", type: "string", required: true }],
  },
  {
    type: "browser.click",
    displayName: "Click",
    category: "Browser",
    description: "Clicks an element.",
    icon: "pointer",
    agentTool: true,
    props: [{ name: "selector", label: "Selector", type: "selector", required: true }, ...healing],
  },
  {
    type: "browser.type",
    displayName: "Type Into",
    category: "Browser",
    description: "Types text into an input.",
    icon: "keyboard",
    agentTool: true,
    props: [
      { name: "selector", label: "Selector", type: "selector", required: true },
      { name: "text", label: "Text", type: "string", required: true },
      { name: "clear", label: "Clear first", type: "boolean", default: true },
      { name: "pressEnter", label: "Press Enter after", type: "boolean", default: false },
      ...healing,
    ],
  },
  {
    type: "browser.select",
    displayName: "Select Option",
    category: "Browser",
    description: "Chooses an option in a dropdown list (by value or visible label).",
    icon: "list",
    agentTool: true,
    props: [
      { name: "selector", label: "Selector", type: "selector", required: true },
      { name: "value", label: "Option", type: "string", required: true },
      ...healing,
    ],
  },
  {
    type: "browser.getText",
    displayName: "Get Text",
    category: "Browser",
    description: "Reads the visible text of an element.",
    icon: "text",
    agentTool: true,
    props: [{ name: "selector", label: "Selector", type: "selector", required: true }, output(), ...healing],
  },
  {
    type: "browser.waitFor",
    displayName: "Wait For Element",
    category: "Browser",
    description: "Waits until an element is visible.",
    icon: "hourglass",
    props: [
      { name: "selector", label: "Selector", type: "selector", required: true },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 30000 },
      ...healing,
    ],
  },
  {
    type: "browser.screenshot",
    displayName: "Take Screenshot",
    category: "Browser",
    description: "Saves a screenshot of the current page.",
    icon: "camera",
    props: [{ name: "path", label: "File path", type: "string", default: "screenshot.png" }],
  },
  {
    type: "browser.close",
    displayName: "Close Browser",
    category: "Browser",
    description: "Closes the browser.",
    icon: "close",
    props: [],
  },

  /* ------------------------ Desktop (Windows UI) ------------------------ */
  {
    type: "desktop.launch",
    displayName: "Start Application",
    category: "Desktop",
    description: "Starts a Windows program (e.g. notepad.exe or a full path) and waits until it is ready.",
    icon: "rocket",
    agentTool: true,
    props: [
      { name: "path", label: "Program", type: "string", required: true, description: "Program name or full path, e.g. notepad.exe" },
      { name: "args", label: "Arguments", type: "string" },
      { name: "waitFor", label: "Wait for window", type: "selector", description: "Optional desktop selector of the window to wait for, e.g. window[process=\"notepad\"]" },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 30000 },
      output("Save process ID to"),
    ],
  },
  {
    type: "desktop.click",
    displayName: "Click (Desktop)",
    category: "Desktop",
    description: "Clicks a button, menu item, checkbox or other element in a Windows application.",
    icon: "pointer",
    agentTool: true,
    props: [
      { name: "selector", label: "Selector", type: "selector", required: true },
      { name: "button", label: "Mouse button", type: "enum", options: ["left", "right"], default: "left" },
      { name: "double", label: "Double click", type: "boolean", default: false },
      {
        name: "mode",
        label: "Click method",
        type: "enum",
        options: ["auto", "mouse"],
        default: "auto",
        description: "auto uses UI Automation (works even if the window is covered); mouse moves the real pointer",
      },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 10000 },
      ...healing,
    ],
  },
  {
    type: "desktop.type",
    displayName: "Type Into (Desktop)",
    category: "Desktop",
    description: "Types text into a field of a Windows application.",
    icon: "keyboard",
    agentTool: true,
    props: [
      { name: "selector", label: "Selector", type: "selector", required: true },
      { name: "text", label: "Text", type: "string", required: true },
      { name: "clear", label: "Clear first", type: "boolean", default: true },
      { name: "pressEnter", label: "Press Enter after", type: "boolean", default: false },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 10000 },
      ...healing,
    ],
  },
  {
    type: "desktop.sendKeys",
    displayName: "Send Keys",
    category: "Desktop",
    description: "Sends keystrokes, e.g. ^s for Ctrl+S, %{F4} for Alt+F4, {ENTER}, {TAB}.",
    icon: "keyboard",
    agentTool: true,
    props: [
      { name: "keys", label: "Keys", type: "string", required: true, description: "SendKeys syntax: ^ = Ctrl, % = Alt, + = Shift, {ENTER}, {TAB}, {F5}" },
      { name: "selector", label: "Focus element first", type: "selector" },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 10000 },
      ...healing,
    ],
  },
  {
    type: "desktop.getText",
    displayName: "Get Text (Desktop)",
    category: "Desktop",
    description: "Reads the value or text of an element in a Windows application.",
    icon: "text",
    agentTool: true,
    props: [
      { name: "selector", label: "Selector", type: "selector", required: true },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 10000 },
      output(),
      ...healing,
    ],
  },
  {
    type: "desktop.select",
    displayName: "Select Item (Desktop)",
    category: "Desktop",
    description: "Chooses an item in a dropdown or list of a Windows application.",
    icon: "list",
    agentTool: true,
    props: [
      { name: "selector", label: "Selector", type: "selector", required: true },
      { name: "value", label: "Item", type: "string", required: true },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 10000 },
      ...healing,
    ],
  },
  {
    type: "desktop.readTable",
    displayName: "Read Table (Desktop)",
    category: "Desktop",
    description: "Reads a grid or list into rows (a list of objects when the table has column headers).",
    icon: "table",
    props: [
      { name: "selector", label: "Selector", type: "selector", required: true },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 10000 },
      output(),
      ...healing,
    ],
  },
  {
    type: "desktop.waitFor",
    displayName: "Wait For Element (Desktop)",
    category: "Desktop",
    description: "Waits until an element or window appears (or disappears).",
    icon: "hourglass",
    props: [
      { name: "selector", label: "Selector", type: "selector", required: true },
      { name: "state", label: "Wait until", type: "enum", options: ["visible", "gone"], default: "visible" },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 30000 },
      ...healing,
    ],
  },
  {
    type: "desktop.screenshot",
    displayName: "Take Screenshot (Desktop)",
    category: "Desktop",
    description: "Saves a screenshot of the screen or of one window/element.",
    icon: "camera",
    props: [
      { name: "path", label: "File path", type: "string", default: "desktop.png" },
      { name: "selector", label: "Element (optional)", type: "selector" },
    ],
  },
  {
    type: "desktop.closeWindow",
    displayName: "Close Window",
    category: "Desktop",
    description: "Closes a window of a Windows application.",
    icon: "close",
    agentTool: true,
    props: [
      { name: "selector", label: "Window selector", type: "selector", required: true },
      { name: "timeoutMs", label: "Timeout (ms)", type: "number", default: 10000 },
    ],
  },

  /* ----------------------------- Excel & CSV ------------------------------ */
  {
    type: "excel.read",
    displayName: "Read Excel",
    category: "Excel & CSV",
    description: "Reads a worksheet from an .xlsx file into a list of rows.",
    icon: "table",
    agentTool: true,
    props: [
      { name: "path", label: "File path", type: "string", required: true },
      { name: "sheet", label: "Sheet", type: "string", description: "Sheet name. Empty = first sheet." },
      {
        name: "hasHeader",
        label: "First row is header",
        type: "boolean",
        default: true,
        description: "When on, each row becomes an object keyed by the header names.",
      },
      output("Save rows to"),
    ],
  },
  {
    type: "excel.write",
    displayName: "Write Excel",
    category: "Excel & CSV",
    description: "Writes a list of rows to a worksheet in an .xlsx file (creates the file if needed).",
    icon: "table",
    props: [
      { name: "path", label: "File path", type: "string", required: true },
      { name: "sheet", label: "Sheet", type: "string", default: "Sheet1" },
      { name: "rows", label: "Rows", type: "expression", required: true, description: "A list of objects or a list of lists." },
      { name: "append", label: "Append to existing rows", type: "boolean", default: false },
    ],
  },
  {
    type: "csv.read",
    displayName: "Read CSV",
    category: "Excel & CSV",
    description: "Reads a CSV file into a list of rows.",
    icon: "table",
    agentTool: true,
    props: [
      { name: "path", label: "File path", type: "string", required: true },
      { name: "delimiter", label: "Delimiter", type: "string", default: "," },
      { name: "hasHeader", label: "First row is header", type: "boolean", default: true },
      output("Save rows to"),
    ],
  },
  {
    type: "csv.write",
    displayName: "Write CSV",
    category: "Excel & CSV",
    description: "Writes a list of rows to a CSV file.",
    icon: "table",
    props: [
      { name: "path", label: "File path", type: "string", required: true },
      { name: "rows", label: "Rows", type: "expression", required: true, description: "A list of objects or a list of lists." },
      { name: "delimiter", label: "Delimiter", type: "string", default: "," },
      { name: "append", label: "Append to existing file", type: "boolean", default: false },
    ],
  },

  /* --------------------------------- Email -------------------------------- */
  {
    type: "email.send",
    displayName: "Send Email",
    category: "Email",
    description: "Sends an email through an SMTP server.",
    icon: "message",
    props: [
      { name: "server", label: "SMTP server", type: "string", required: true, description: "host:port, e.g. smtp.office365.com:587" },
      { name: "credential", label: "Credential asset", type: "string", required: true, description: "Name of a credential asset with the mailbox username and password." },
      { name: "from", label: "From", type: "string", description: "Empty = the credential's username." },
      { name: "to", label: "To", type: "string", required: true, description: "One or more addresses, separated by commas." },
      { name: "cc", label: "Cc", type: "string" },
      { name: "subject", label: "Subject", type: "string", required: true },
      { name: "body", label: "Body", type: "text", required: true },
      { name: "html", label: "Body is HTML", type: "boolean", default: false },
      { name: "attachments", label: "Attachments", type: "expression", description: "A list of file paths, e.g. [\"report.xlsx\"]." },
    ],
  },
  {
    type: "email.read",
    displayName: "Read Emails",
    category: "Email",
    description: "Reads messages from a mailbox folder over IMAP. Result: a list of { from, to, subject, date, text, attachments }.",
    icon: "message",
    props: [
      { name: "server", label: "IMAP server", type: "string", required: true, description: "host:port, e.g. outlook.office365.com:993" },
      { name: "credential", label: "Credential asset", type: "string", required: true, description: "Name of a credential asset with the mailbox username and password." },
      { name: "folder", label: "Folder", type: "string", default: "INBOX" },
      { name: "unreadOnly", label: "Unread only", type: "boolean", default: true },
      { name: "limit", label: "Maximum messages", type: "number", default: 10 },
      { name: "markAsRead", label: "Mark as read", type: "boolean", default: false },
      { name: "attachmentsFolder", label: "Save attachments to", type: "string", description: "Folder for attachments. Empty = don't save them." },
      output("Save messages to"),
    ],
  },

  /* ---------------------------------- PDF --------------------------------- */
  {
    type: "pdf.readText",
    displayName: "Read PDF Text",
    category: "PDF",
    description: "Extracts the text of a PDF. Combine with AI Extract Data to pull fields out of invoices or forms.",
    icon: "file",
    agentTool: true,
    props: [{ name: "path", label: "File path", type: "string", required: true }, output("Save text to")],
  },
  {
    type: "pdf.merge",
    displayName: "Merge PDFs",
    category: "PDF",
    description: "Combines several PDF files into one.",
    icon: "file",
    props: [
      { name: "files", label: "Files", type: "expression", required: true, description: "A list of PDF paths, in order." },
      { name: "path", label: "Output file", type: "string", required: true },
    ],
  },

  /* ------------------------------ Work queues ----------------------------- */
  {
    type: "queue.add",
    displayName: "Add Queue Item",
    category: "Work Queues",
    description: "Adds a work item to a queue, for example one per invoice, for bots to process.",
    icon: "list",
    props: [
      { name: "queue", label: "Queue", type: "string", required: true },
      { name: "data", label: "Data", type: "json", required: true, description: "The item's data, e.g. {\"invoice\": \"{{ row.number }}\"}" },
      { name: "reference", label: "Reference", type: "string", description: "Optional business key, e.g. an invoice number. Duplicates are rejected." },
      output("Save item id to"),
    ],
  },
  {
    type: "queue.getNext",
    displayName: "Get Next Queue Item",
    category: "Work Queues",
    description: "Takes the next waiting item from a queue and locks it for this job. The result is empty when the queue has no work.",
    icon: "list",
    props: [{ name: "queue", label: "Queue", type: "string", required: true }, output("Save item to")],
  },
  {
    type: "queue.complete",
    displayName: "Set Queue Item Result",
    category: "Work Queues",
    description: "Marks a queue item as done. Failed items are retried automatically; business exceptions are not.",
    icon: "list",
    props: [
      { name: "item", label: "Item", type: "expression", required: true, description: "The item from Get Next Queue Item, or its id." },
      { name: "status", label: "Status", type: "enum", options: ["successful", "failed", "business-exception"], default: "successful" },
      { name: "result", label: "Result data", type: "json" },
      { name: "message", label: "Message", type: "string", description: "Reason for a failure or business exception." },
    ],
  },

  /* ---------------------------------- AI ---------------------------------- */
  {
    type: "ai.prompt",
    displayName: "AI Prompt",
    category: "AI",
    description: "Sends a prompt to Claude and saves the text answer.",
    icon: "sparkles",
    props: [
      { name: "prompt", label: "Prompt", type: "text", required: true },
      { name: "system", label: "System instructions", type: "text" },
      output(),
    ],
  },
  {
    type: "ai.extract",
    displayName: "AI Extract Data",
    category: "AI",
    description: "Extracts structured data (matching a JSON Schema) from text, e.g. an email or invoice.",
    icon: "table",
    props: [
      { name: "input", label: "Input text", type: "string", required: true },
      { name: "instructions", label: "Instructions", type: "text" },
      {
        name: "schema",
        label: "JSON Schema",
        type: "json",
        required: true,
        description: "Object schema. Every object needs `required` and `additionalProperties: false`.",
      },
      output(),
    ],
  },
  {
    type: "ai.agent",
    displayName: "AI Agent",
    category: "AI",
    description:
      "Gives Claude a goal and lets it decide which actions to run (browser, HTTP, files) until the goal is met.",
    icon: "robot",
    props: [
      { name: "goal", label: "Goal", type: "text", required: true },
      {
        name: "tools",
        label: "Allowed actions",
        type: "json",
        description: "Array of action types the agent may use. Defaults to every agent-capable action.",
      },
      { name: "maxSteps", label: "Max steps", type: "number", default: 20 },
      output("Save final answer to"),
    ],
  },
];

export function findAction(type: string, catalog: ActionMeta[] = BUILTIN_ACTIONS): ActionMeta | undefined {
  return catalog.find((a) => a.type === type);
}
